import { execFileSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it } from "vitest";

/** The five files as the repo has them, in miniature. */
const FILES: Record<string, string> = {
  "package.json": '{\n  "name": "audiosyncmaster",\n  "version": "2.10.0",\n  "type": "module"\n}\n',
  "package-lock.json":
    '{\n  "name": "audiosyncmaster",\n  "version": "2.10.0",\n  "lockfileVersion": 3,\n  "packages": {\n    "": {\n      "name": "audiosyncmaster",\n      "version": "2.10.0"\n    },\n    "node_modules/x": {\n      "version": "1.0.0"\n    }\n  }\n}\n',
  "src-tauri/tauri.conf.json": '{\n  "productName": "AudioSyncMaster",\n  "version": "2.10.0",\n  "build": {\n    "devUrl": "http://localhost:8081"\n  }\n}\n',
  "src-tauri/Cargo.toml": '[package]\nname = "audiosyncmaster"\nversion = "2.10.0"\nedition = "2021"\n\n[dependencies]\nserde = { version = "1", features = ["derive"] }\n',
  "src-tauri/Cargo.lock":
    '# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = "aho-corasick"\nversion = "1.1.3"\n\n[[package]]\nname = "audiosyncmaster"\nversion = "2.10.0"\ndependencies = [\n "serde",\n]\n\n[[package]]\nname = "serde"\nversion = "1.0.0"\n',
};

const SCRIPT = path.resolve(__dirname, "set-version.cjs");
const roots: string[] = [];

/** A throwaway checkout with the script in its own scripts/ folder, so the
 *  script's "the repo is my parent" holds; `eol` is how it was checked out. */
function checkout(eol: "\n" | "\r\n"): string {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "set-version-"));
  roots.push(root);
  fs.mkdirSync(path.join(root, "scripts"));
  fs.mkdirSync(path.join(root, "src-tauri"));
  fs.copyFileSync(SCRIPT, path.join(root, "scripts", "set-version.cjs"));
  for (const [name, text] of Object.entries(FILES)) {
    fs.writeFileSync(path.join(root, name), text.replace(/\n/g, eol));
  }
  return root;
}

function run(root: string, version: string): string {
  return execFileSync(process.execPath, [path.join(root, "scripts", "set-version.cjs"), version], { encoding: "utf8" });
}

afterEach(() => {
  for (const root of roots.splice(0)) fs.rmSync(root, { recursive: true, force: true });
});

describe.each([
  ["LF", "\n" as const],
  ["CRLF", "\r\n" as const],
])("set-version on a %s checkout", (_label, eol) => {
  it("writes the version into all five files and leaves everything else as it was", () => {
    const root = checkout(eol);
    const out = run(root, "2.11.0");
    expect(out).toContain("version 2.11.0 written");
    for (const [name, original] of Object.entries(FILES)) {
      const after = fs.readFileSync(path.join(root, name), "utf8");
      // Only the root package's number changed: the file is the original
      // with 2.10.0 -> 2.11.0 where it named the package.
      const expected = original.replace(/2\.10\.0/g, "2.11.0").replace(/\n/g, eol);
      expect(after, name).toBe(expected);
    }
  });

  it("keeps the lockfile's other versions and its dependency tables untouched", () => {
    const root = checkout(eol);
    run(root, "3.0.0");
    const lock = fs.readFileSync(path.join(root, "src-tauri", "Cargo.lock"), "utf8");
    expect(lock).toContain(`name = "audiosyncmaster"${eol}version = "3.0.0"`);
    expect(lock).toContain(`name = "serde"${eol}version = "1.0.0"`);
    expect(lock).toContain(`name = "aho-corasick"${eol}version = "1.1.3"`);
    const npm = JSON.parse(fs.readFileSync(path.join(root, "package-lock.json"), "utf8"));
    expect(npm.packages["node_modules/x"].version).toBe("1.0.0");
  });
});

it("refuses a number that is not MAJOR.MINOR.PATCH", () => {
  const root = checkout("\n");
  expect(() => run(root, "2.11")).toThrow();
  expect(fs.readFileSync(path.join(root, "package.json"), "utf8")).toContain('"version": "2.10.0"');
});
